# specify docker-compose version
version: '2'

# Define the services/containers to be run
services:
  client: # name of the service
    build: Client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forwarding

  server:
    build: Server
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 Main.js
    # links:
    #   - mongodb # link this service to the database service

  # mongodb: # name of the third service
  #   image: mongo # specify image to build container from
  #   ports:
  #     - "27017:27017" # specify port forwarding